### ISSUE TITLE
largeicon 변경

### ISSUE THREAD

**Issue by nwlee7950** [pdjdev/bokboot#9]
largeicon.png

이 아이콘이 눈에 잘 띄지 않는 것 같아요.

다른 아이콘이나 색상이 변경되면 더 좋을것 같습니다.

**Comment by pdjdev** [comment]
![image](https://user-images.githubusercontent.com/24975076/102688693-b4473000-423b-11eb-97d5-5842e2d35eff.png)

이슈 감사합니다. 확실히 작업 표시줄과 같은 작은 크기에서는 시인성이 좋지 못한 것 같습니다.
해당 사항은 수정해 보도록 하겠습니다.
